### ISSUE TITLE
KeyError: 'localFriction' in cpt_module.py

### ISSUE THREAD

**Issue by TAVMWB** [rivm-syso/OURS#11]
Hello, 

I'm trying to run the example file in [OURS v2.0](https://github.com/rivm-syso/OURS/releases/tag/v.2.0.0), however I keep getting the error "No ground data available" in the GUI. 
I ran `cpt_tool.py` separately from a command prompt as described in [this issue](https://github.com/rivm-syso/OURS/issues/8#issuecomment-1269853762) to see which error occurs exactly, which had the following output: 

```
C:\Program Files\RIVM\OURS-UI 2.0\python>Python.exe cpt_tool.py -i"D:\Users\XXXX\Documents\Projectdocumenten\OURS\input.json" -o "D:\Users\XXXX\Documents\Projectdocumenten\OURS"
WARNING:root:Checking if index exists, if index does not exist it should be created, this may take a while...
WARNING:root:Found 121 CPTs in intersecting polygons.
WARNING:root:Found 0 CPTs in circle.
Traceback (most recent call last):
  File "C:\Program Files\RIVM\OURS-UI 2.0\python\pandas\core\indexes\base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
    cpdef get_loc(self, object val):
  File "pandas\_libs\index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
    return self.mapping.get_item(val)
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'localFriction'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\RIVM\OURS-UI 2.0\python\cpt_tool.py", line 389, in <module>
    analysis(props, methods, settings, args.output, args.plots)
  File "C:\Program Files\RIVM\OURS-UI 2.0\python\cpt_tool.py", line 307, in analysis
    jsn, is_jsn_modified = read_cpt(data, methods_cpt, settings_cpt, output, properties, plots, idx,
  File "C:\Program Files\RIVM\OURS-UI 2.0\python\cpt_tool.py", line 191, in read_cpt
    data_quality = cpt.parse_bro(cpt_BRO[idx_cpt],
  File "C:\Program Files\RIVM\OURS-UI 2.0\python\cpt_module.py", line 104, in parse_bro
    if all(cpt["dataframe"][k] == 0):
  File "C:\Program Files\RIVM\OURS-UI 2.0\python\pandas\core\frame.py", line 3506, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Program Files\RIVM\OURS-UI 2.0\python\pandas\core\indexes\base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'localFriction'
```

I am using the latest BRO data, `brocptvolledigeset.gpkg`, downloaded from https://service.pdok.nl/bzk/brocptvolledigeset/atom/v1_0/downloads/brocptvolledigeset.zip.

I also updated the file `bro.py` with the latest version on this repository, however this resulted in the same error. 

How can I get OURS working?

**Comment by AnnaNieuwenhuis** [comment]
Hi, I have a similar issue. I used `bro.py` and `cpt_tool.py` from version 2.1.0. However, when I run the command as described I get a different result.

`C:\MijnProgrammaMap\OURS-UI 2.0\python>Python.exe cpt_tool.py -i "D:\test_ours\input.json" -o ":D\test_ours"
Traceback (most recent call last):
  File "C:\MijnProgrammaMap\OURS-UI 2.0\python\cpt_tool.py", line 10, in <module>
    from CPTtool import bro
ModuleNotFoundError: No module named 'CPTtool'`

So I have two questions; does anyone know why I get this ModuleNotFoundError, and has anyone solved the problem yet described above? Thanks.
