### ISSUE TITLE
Error No ground data available

### ISSUE THREAD

**Issue by PH0TRA** [rivm-syso/OURS#8]
Ours 2.0 stops when it tries to calculate the ground module:
Error	8-2-2022 17:50:29	Error in module "cpt_tool.py". Exit code: 0!
It appears on my own input xml's but not on the default input.xml
brocptvolledigeset.gpkg is installed in the right directorry

**Comment by vArup** [comment]
I'm having this problem too... were you able to fix it?

**Comment by ArnaudYK** [comment]
If it works on the default input.xml it could be that there is a problem with a cpt. We are busy with the release of version 2.1. In the mean time please download a new cpt_tool.py from this repository and replace the one that was installed.

**Comment by B2BWild** [comment]
Replacing cpt_tool.py did not work. This makes sense as the file in the repository is not different from the one in the install folder.
Replacing bro.py with the one from the repo did work however!

**Comment by raphuel** [comment]
My version worked before, but now I receive this error message: "Error in script "cpt_tool.py" during calculation.
Input JSON is now located in "C:\Users\d08334\AppData\Local\Temp\OURS_11196\"."

Replacing cpt_tool.py and bro.py did not work, most likely since dates/versions are exactly the same.

Any ideas on this?

**Comment by ArnaudYK** [comment]
Hi. 

The best way to get relevant feedback is to run the cpt_tool seperatly. That will give more specific error messages. The way to do this is as follows: 

Run OURS as before
Go to the location shown in error box (TEMP\OURS_XXXX)
Copy the file input.json to some other location
Start a command prompt (cmd.exe)
Go to you ours installation directory and subdirectory Python
Run: Python.exe cpt_tool.py -I [inputfilepath]\input.json -o [outputpathname]

In your console you may be able to see the error messages. Copy these and post them.

**Comment by raphuel** [comment]
Hi Arnoud, is this what you asked for:

C:\Program Files\RIVM\OURS-UI 2.0\python>Python.exe cpt_tool.py -i "C:\Users\d08334\Downloads\Python test\input.json" -o "C:\Users\d08334\Downloads\Python test\"
Traceback (most recent call last):
  File "C:\Program Files\RIVM\OURS-UI 2.0\python\cpt_tool.py", line 389, in <module>
    analysis(props, methods, settings, args.output, args.plots)
  File "C:\Program Files\RIVM\OURS-UI 2.0\python\cpt_tool.py", line 277, in analysis
    log_file = log_handler.LogFile(output, idx)
  File "C:\Program Files\RIVM\OURS-UI 2.0\python\log_handler.py", line 11, in __init__
    os.makedirs(output_folder)
  File "C:\Program Files\RIVM\OURS-UI 2.0\python\python310.zip\os.py", line 225, in makedirs
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\d08334\\Downloads\\Python test"'

I attached the screenshot as well.
![Screenshot 2022-10-07 112407 Python](https://user-images.githubusercontent.com/54445074/194520989-331c654c-f16c-475a-ad8c-9ed3d402d18d.png)

**Comment by ArnaudYK** [comment]
Almost. Please do not use the last \  The command in de text is correct, so is is:
Python.exe cpt_tool.py -i "C:\Users\d08334\Downloads\Python test\input.json" -o "C:\Users\d08334\Downloads\Python test"
instead of:
Python.exe cpt_tool.py -i "C:\Users\d08334\Downloads\Python test\input.json" -o "C:\Users\d08334\Downloads\Python test\ "

(used a trailing space because github removes the \ if it is followed by a " )

**Comment by raphuel** [comment]
Ah, this gives another output Arnoud:

C:\Program Files\RIVM\OURS-UI 2.0\python>Python.exe cpt_tool.py -i "C:\Users\d08334\Downloads\Python test\input.json" -o "C:\Users\d08334\Downloads\Python test"
WARNING:root:Checking if index exists, if index does not exist it should be created, this may take a while...
WARNING:root:Found 121 CPTs in intersecting polygons.
WARNING:root:Found 0 CPTs in circle.
Traceback (most recent call last):
  File "C:\Program Files\RIVM\OURS-UI 2.0\python\pandas\core\indexes\base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
    cpdef get_loc(self, object val):
  File "pandas\_libs\index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
    return self.mapping.get_item(val)
  File "pandas\_libs\hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'localFriction'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\RIVM\OURS-UI 2.0\python\cpt_tool.py", line 389, in <module>
    analysis(props, methods, settings, args.output, args.plots)
  File "C:\Program Files\RIVM\OURS-UI 2.0\python\cpt_tool.py", line 307, in analysis
    jsn, is_jsn_modified = read_cpt(data, methods_cpt, settings_cpt, output, properties, plots, idx,
  File "C:\Program Files\RIVM\OURS-UI 2.0\python\cpt_tool.py", line 191, in read_cpt
    data_quality = cpt.parse_bro(cpt_BRO[idx_cpt],
  File "C:\Program Files\RIVM\OURS-UI 2.0\python\cpt_module.py", line 104, in parse_bro
    if all(cpt["dataframe"][k] == 0):
  File "C:\Program Files\RIVM\OURS-UI 2.0\python\pandas\core\frame.py", line 3506, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\Program Files\RIVM\OURS-UI 2.0\python\pandas\core\indexes\base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'localFriction'

Again, I attached a screenshot.
![Screenshot 2022-10-07 114917 Python 2](https://user-images.githubusercontent.com/54445074/194526088-553ceb2a-5501-46cc-bb0c-004b7a26fa72.png)

**Comment by ArnaudYK** [comment]
Did you download the more recent bro.py?
![image](https://user-images.githubusercontent.com/62339673/194526464-d4a396ca-d1b4-401e-a9fa-53ba8fdeef2b.png)

Copy it to the python subdirectory under OURS. This version is slightly newer than the release. (we are preparing a new release with an updated building module). This bro.py should check if all required columns are there (in your case it seems one is missing).

**Comment by raphuel** [comment]
I did Arnoud, but the file is of the exact same date and time as the most recent one. Does not make a difference.

**Comment by ArnaudYK** [comment]
Can you double check. 
![image](https://user-images.githubusercontent.com/62339673/194528570-a363e634-d372-4467-b301-014307967ece.png)
The red lines snot be there and the green lines should be in the bro.py.

If this is the same please attach the input.json and I will try to find out what is wrong.

**Comment by raphuel** [comment]
Hmmm... the red lines are there. 
[input.zip](https://github.com/rivm-syso/OURS/files/9733047/input.zip)

**Comment by ArnaudYK** [comment]
Try this one then. It should contain the green lines.
[bro.zip](https://github.com/rivm-syso/OURS/files/9733117/bro.zip)

**Comment by raphuel** [comment]
Hey Arnaud, this seems to have solved the problem. Thanks..
